LOAD DATA LOCAL INFILE 'sellers_sorted.csv' INTO TABLE Sellers FIELDS TERMINATED BY '|*|';

LOAD DATA LOCAL INFILE 'bidders_sorted.csv' INTO TABLE Bidders FIELDS TERMINATED BY '|*|';

LOAD DATA LOCAL INFILE 'itemList.csv' INTO TABLE Items FIELDS TERMINATED BY '|*|';

LOAD DATA LOCAL INFILE 'bids.csv' INTO TABLE Bids FIELDS TERMINATED BY '|*|';

LOAD DATA LOCAL INFILE 'categories_sorted.csv' INTO TABLE Categories FIELDS TERMINATED BY '|*|';

